
// src/components/properties/detail/TerraScribeDisplayCard.tsx
"use client";

import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Edit3, Sparkles } from "lucide-react";

interface TerraScribeDisplayCardProps {
  description: string;
  onRefine: () => void;
}

export function TerraScribeDisplayCard({ description, onRefine }: TerraScribeDisplayCardProps) {
  return (
    <Card className="shadow-lg bg-card">
      <CardHeader>
        <CardTitle className="font-headline text-xl text-primary">About this Property</CardTitle>
      </CardHeader>
      <CardContent>
        <p className="text-foreground leading-relaxed whitespace-pre-line">
          {description}
        </p>
      </CardContent>
      <CardFooter className="flex justify-end items-center pt-4 border-t border-border">
        <span className="text-xs text-muted-foreground mr-2 flex items-center">
            <Sparkles className="h-3 w-3 mr-1 text-primary/80" /> Generated by TerraScribe™
        </span>
        <Button variant="link" onClick={onRefine} className="p-0 h-auto text-primary">
          <Edit3 className="mr-1 h-3 w-3" /> Refine
        </Button>
      </CardFooter>
    </Card>
  );
}

    