
"use client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Mic, Send, FileSignature, Shield } from "lucide-react";
import Image from "next/image";
import Link from "next/link";

const WaveformDot = () => <div className="waveform-dot" />;


export function AiAssistantCard() {
  return (
    <div className="bg-slate-800 p-6 rounded-xl shadow-xl h-full flex flex-col text-slate-100">
      <div className="flex items-center gap-3 mb-4">
        <div className="w-10 h-10 bg-gradient-to-br from-primary to-teal-400 rounded-full flex items-center justify-center">
          <Image src="https://placehold.co/40x40.png?text=AI" alt="AI Avatar" width={24} height={24} className="rounded-full invert brightness-0 data-ai-hint='abstract geometric'" />
        </div>
        <h2 className="text-xl font-semibold">AI Assistant</h2>
      </div>

      <div className="flex-grow flex flex-col items-center justify-center my-4 text-center">
        <p className="text-slate-300 mb-4 text-sm px-2">
           "The Sale Agreement has been generated by TerraScribe™. The buyer's E-Khata has been uploaded and is currently being verified by TerraSecure™. I'll notify you the moment the verification is complete."
        </p>
      </div>

      <div className="space-y-3 mb-5">
        <h3 className="text-center text-xs font-semibold uppercase text-slate-400">Quick Actions</h3>
        <div className="flex justify-center gap-2">
            <Button variant="outline" size="sm" asChild className="bg-slate-700 border-slate-600 hover:bg-slate-600 text-slate-200">
                <Link href="/scribe">
                    <FileSignature className="h-4 w-4 mr-2" /> Generate RERA Doc
                </Link>
            </Button>
             <Button variant="outline" size="sm" asChild className="bg-slate-700 border-slate-600 hover:bg-slate-600 text-slate-200">
                <Link href="/documents">
                    <Shield className="h-4 w-4 mr-2" /> Verify E-Khata
                </Link>
            </Button>
        </div>
      </div>
      
      <div className="relative mt-auto">
        <Input
          type="text"
          placeholder="Ask about a deal, document, or compliance status..."
          className="bg-slate-700 border-slate-600 text-slate-200 placeholder-slate-400 rounded-lg pl-4 pr-20 h-12 text-sm focus:ring-primary focus:border-primary"
        />
        <div className="absolute right-2 top-1/2 -translate-y-1/2 flex items-center gap-1">
            <Button variant="ghost" size="icon" className="text-slate-400 hover:text-primary h-9 w-9">
                <Mic className="h-4 w-4" />
            </Button>
            <Button variant="ghost" size="icon" className="text-slate-400 hover:text-primary h-9 w-9">
                <Send className="h-4 w-4" />
            </Button>
        </div>
      </div>
    </div>
  );
}
